name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "Makefile"
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go: ["1.22", "1.23"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test -v
