name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Build gurl
        run: bash build.sh
      - name: Test
        run: gunzip gurl-linux-x86_64.gz && ./gurl-linux-x86_64 -h
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gurl-*.gz"
